### ISSUE TITLE
Server error when trying to reset password

### ISSUE THREAD

**Issue by arp242** [BeWelcome/rox#132]
If I go to https://www.bewelcome.org/resetpassword and enter `arp242` as my username, the server responds with a 500 and `Unfortunately the server ran into an error and your request can't be fulfilled.`

**Comment by thisismeonmounteverest** [comment]
One of the many bugs already fixed on https://beta.bewelcome.org/resetpassword. Please try this.

**Comment by arp242** [comment]
Oh, cool. That also gives me a 500 after submitting though.

---

BTW the error page says:

> Page not found
>
> Unfortunately the server ran into an error and your request can't be fulfilled.

Which is a bit strange, as an error is not really the same as "Page not found".

Also, the submit button has the text `label.reset.password`.

**Comment by thisismeonmounteverest** [comment]
Okay, the button needed a translation. That should be fixed now.

Could you try again, I guess the code was annoyed by the fact that you signed up and left at some point...

**Comment by arp242** [comment]
The button is correct now, so I assume the new code is deployed, but I still get a server error when using `arp242`. I tried Chrome as well to ensure there isn't any cookies or other state interfering, and have the same results.

**Comment by thisismeonmounteverest** [comment]
No, the button label just changes because I added the translation (comes from the database no code changes needed).

I check the logs on the server when I get a chance to access it (can't from the work environment).

**Comment by arp242** [comment]
Ah right 😅

No hurries! Thanks for looking.

**Comment by thisismeonmounteverest** [comment]
I switch off the work laptop :)

Turns out your old profile was buggy and could be resurrected. I freed your username you should be able to signup now (use beta for that nicer experience :))

**Comment by arp242** [comment]
I tried to sign up (on the beta), walked to all the steps, and for a server error again after the last step 😅

When I try to login I get `login.mail.not_confirmed`, but I haven't received a confirmation email. If I click the "resend email" button I end up on https://beta.bewelcome.org/signup/resend/arp242 and another server error 😅

The email I used is martin@arp242.net

Aside: my language is set to Breton by default for some reason 🤔

**Comment by thisismeonmounteverest** [comment]
I renamed a parameter for a route yesterday and didn't use it everywhere.

Please try again.

**Comment by thisismeonmounteverest** [comment]
Regarding language: Someone reported that the landing page doesn't show the language of the browser and I tried to figure out why not and the current default therefore is still Breton :)

**Comment by arp242** [comment]
Cheerio, I managed to sign up now.

There's a small spelling error on the confirmation page btw: `We send you a new notification containing your confirmation link.` This should be "sent" (past tense).

I get an error changing the language from Dutch to English on https://beta.bewelcome.org/mypreferences – if I reload the settings page it's set to English, but the interface is still in Dutch. It seems to work correct on the non-beta page which is in English.

**Comment by thisismeonmounteverest** [comment]
On www the change is only visible after logout and re-login. Beta should reload the page in the preferred language but slips on something (I'm pretty sure it worked when I implemented that :)).

**Comment by thisismeonmounteverest** [comment]
This should now also work on beta.

**Comment by crumbking** [comment]
Tested on beta with crumbking_testuser. Thought I did not get the reset mail. But not sure which mail address I used. Maybe its a good idea to mention the mail address in the sentence:

"We just sent you a mail with a link that allows you to reset your password."
Or could this raise abuse problems? 

Regarding the other issue in preference:
Changed from English to Dutch and back on beta. Works. Translation issue left:

PreferredLanguageSetFlashNotice 

Report that into translation group. 
Who had the idea to notice something in orange /red which works ;-)

@arp242 Please check once again and feel free to close the issue(s).

**Comment by crumbking** [comment]
Closing as no feedback and code is already live.
