### ISSUE TITLE
Fix unit tests for infection

### ISSUE THREAD

**Issue by vincentchalamon** [BeWelcome/rox#186]
Some unit tests allow mutation escape:
```bash
phpdbg -qrr bin/phpunit --coverage-text --coverage-xml=build/logs/phpunit/coverage-xml --coverage-clover=build/logs/phpunit/clover.xml --log-junit=build/logs/phpunit/junit.xml --colors=never
vendor/bin/infection --only-covered --coverage=build/logs/phpunit --min-covered-msi=85 --threads=30
```
Fix them, then add infection tests in CI

**Comment by thisismeonmounteverest** [comment]
Closing as fixed with https://github.com/BeWelcome/rox/commit/b0112296cfae72003ecbb4378d3af7555ea71b12

**Comment by vincentchalamon** [comment]
Infection tests are still failing (cf. https://github.com/BeWelcome/rox/pull/184), check infection.log for more information.

**Comment by thisismeonmounteverest** [comment]
@vincentchalamon They where reporting 90% coverage when I used them on the main branch. Did you add any tests?

**Comment by vincentchalamon** [comment]
Infection testing is not about coverage, it's about unit tests which don't cover all use-cases properly. Check the following log file for more info: [infection.log](https://github.com/BeWelcome/rox/files/5612174/infection.log)

**Comment by thisismeonmounteverest** [comment]
@vincentchalamon The issue is coverage. The configuration for infection in the feature/api branch says the whole src but we only have tests for the stuff in Model at the moment.

Changing that should make the infection test pass:
![image](https://user-images.githubusercontent.com/11598088/100542543-d8ba7880-324a-11eb-84e7-485584722740.png)

**Comment by vincentchalamon** [comment]
I've updated the infection.json.dist configuration file accordingly. We shouldn't forget to update it while adding tests
