### ISSUE TITLE
Bug with gender search filter

### ISSUE THREAD

**Issue by ghost** [BeWelcome/rox#226]
Bug [reported by Polyglot](https://www.bewelcome.org/group/570/forum/s22270-Find_members___filtering_by_gender_not_working), but not solved yet so I post it here :

- The search for a host with gender "other" returns all hosts instead.
- Searches for male and searches for females hosts seem to work on page 1, but display all hosts as soon as I click beyond the first page.

**Comment by thisismeonmounteverest** [comment]
Second part is still open.

**Comment by TillWenke** [comment]
@thisismeonmounteverest it is the other way around. "other" still does not work.

**Comment by nciemniak** [comment]
> The search for a host with gender "other" returns all hosts instead.

Planning to investigate this as a first issue.

**Comment by TillWenke** [comment]
> > The search for a host with gender "other" returns all hosts instead.
> 
> Planning to investigate this as a first issue. Feel free to assign the issue to me, if possible @ghost

I am also just starting. Tried to find out more about the structure of the project here https://github.com/BeWelcome/rox/issues/296#issue-1320094636 hope this helps us at least a bti to get started

**Comment by nciemniak** [comment]
It appears to work properly when I test it locally, i.e. searching for hosts with gender "other" in fact returns only hosts with gender "other." Makes me wonder if it could be a data issue? Has anyone been able to replicate this locally? (maybe @TillWenke, @thisismeonmounteverest ?)

My next route of action would normally be to take a look at the data in the production database (or read replica, if exists), logging in with read-only permissions for safety, but considering I am new, I am reluctant to ask this sort of admin-exclusive access.

**Comment by thisismeonmounteverest** [comment]
@nciemniak Seems I fixed that already :)

Regarding access to production data that would need an NDA but trying it on beta should be enough if your local code is close to the deployed code there.

**Comment by nciemniak** [comment]
@thisismeonmounteverest Nice 👍 
How do I access beta?

Also, I'm still seeing the issue on production, so is the fix only pushed to beta?
